### ISSUE TITLE
Support bp4?

### ISSUE THREAD

**Issue by switz** [pnnl/blueprint-styler#2]
Would love to use this to style bp4 to match bp3 colors. Any plans to upgrade?

**Comment by arniebradfo** [comment]
Yes. I'm working on a [v4](https://github.com/pnnl/blueprint-styler/tree/v4) upgrade, but it will likely be a few more weeks.

**Comment by switz** [comment]
No rush, found just updating the namespace got me pretty far. Thanks again. Will track this issue for more integrated support.

**Comment by arniebradfo** [comment]
v4 is now supported along with a v3 style.

**Comment by switz** [comment]
Hey, any plans to support bp5?

**Comment by arniebradfo** [comment]
Yes. Probably won't be for another few months, but yes.

**Comment by arniebradfo** [comment]
@switz v5 is released
